### ISSUE TITLE
Do Not need to catch SIGKILL

### ISSUE THREAD

**Issue by bwangelme** [yeqown/gowatch#1]
Hello yeqown,

https://github.com/yeqown/go-watcher/blob/master/cmd/go-watcher/main.go#L127-L129

In the above code. You don't need to catch the `SIGKILL`. Because  the signals `SIGKILL` and `SIGSTOP` cannot be caught, blocked, or ignored.

See more on [man 7 signal](http://man7.org/linux/man-pages/man7/signal.7.html)

**Comment by yeqown** [comment]
thanks for reminding
